trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2  
  inputs:
    Contents: 'src/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
- task: FtpUpload@2
  inputs:
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'maxdecor FTP'
    rootDirectory: '$(Build.ArtifactStagingDirectory)/src'
    filePatterns: '**'
    remoteDirectory: '/htdocs/portfolio_daniel'
    clean: false
    cleanContents: false
    preservePaths: true
    trustSSL: true